### ISSUE TITLE
api: Addwatermark concurrency

### ISSUE THREAD

**Issue by Chennnnnnnnnnnnnnnnnn** [pdfcpu/pdfcpu#499]
An error was reported in 'Addwatermark' with concurrent scenarios："fatal error: concurrent map writes"

position：/pkg/pdfcpu/createText.go:419
ttf.UsedGIDs[gid] = true

maybe use sync.map
or how can i resolve it?

**Comment by hhrutter** [comment]
Hello!

Please explain your usecase in order to reproduce this.

Thank you for using pdfcpu 💚

**Comment by Chennnnnnnnnnnnnnnnnn** [comment]
Thanks for reply

It's a REST API for add PDF watermark, error can reproduce when concurrency more than one

```
if _, ok := font.UserFontMetrics["NSimSun"]; !ok {
        font.LoadUserFonts()
}

wm, err := pdfcpu.ParseTextWatermarkDetails(doc.WaterMarkStr, "sc:2 abs, op:.4, pos:c, points:30, rotation:45, fontname:NSimSun", onTop, 1)
	if err != nil {
		return outfile, err
	}

	inFile := bytes.NewReader(doc.File)
	outFile := bytes.NewBuffer(outfile)

	err = api.AddWatermarks(inFile, outFile, nil, wm, nil)
	if err != nil {
		return outfile, err
	}
```

Error info:
```
fatal error: concurrent map writes

```

**Comment by hhrutter** [comment]
Please post the stacktrace you are getting for further analysis.

**Comment by hhrutter** [comment]
This should be fixed with latest release.

**Comment by semvis123** [comment]
Isn't fully fixed yet. The `UserFontMetrics` is still being used without a lock.
```
fatal error: concurrent map writes

goroutine 29 [running]:
github.com/pdfcpu/pdfcpu/pkg/font.LoadUserFonts()
        /Users/user/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.0/pkg/font/metrics.go:247 +0x24a
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.EnsureDefaultConfigAt({0xc005e1c060?, 0xc004f7d900?})
        /Users/user/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.0/pkg/pdfcpu/model/configuration.go:251 +0x150
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.NewDefaultConfiguration()```
