### ISSUE TITLE
Keywords are incorrectly added

### ISSUE THREAD

**Issue by wdscxsj** [pdfcpu/pdfcpu#912]
This issue reports multiple problems with the `keywords` command, mostly related to CJK text and Acrobat interoperability. Tested with pdfcpu v0.8.0 on Windows and Linux. The test files are attached at the end.

1\. Add a keyword `你好` to `empty.pdf`. The listed keyword is `` `} ``:

```
$ pdfcpu keywords add empty.pdf 你好
optimizing...
$ pdfcpu keywords list empty.pdf
optimizing...
`}
```

2\. `empty-12-3.pdf` contains 2 keywords added with Acrobat, `1 2` and `3`, and they can be correctly listed by pdfcpu. Add another keyword `4`, and rename the file to `empty-12-3-4.pdf`. The keywords can be listed as expected by pdfcpu, but not in Acrobat:

```
$ pdfcpu keywords add empty-12-3.pdf 4
optimizing...
$ mv empty-12-3.pdf empty-12-3-4.pdf
$ pdfcpu keywords list empty-12-3-4.pdf
optimizing...
1 2
3
4
```

![12-3-4](https://github.com/pdfcpu/pdfcpu/assets/863369/9e408463-b6e5-4b23-94db-e5bb3c9306a0)

3\. `empty-你好.pdf` contains a keyword `你好` added with Acrobat. Then add a keyword `world`. The keywords listed by pdfcpu are OK, but not in Acrobat:

![你好-world](https://github.com/pdfcpu/pdfcpu/assets/863369/ae019113-3f16-40e0-b43b-f08c32c53b64)

4\. Try again with the original `empty-你好.pdf`, and add a keyword `世界`. The keywords listed by pdfcpu and by Acrobat are both incorrect:

```
$ pdfcpu keywords add empty-你好.pdf 世界
optimizing...
$ pdfcpu keywords list empty-你好.pdf
optimizing...
你好
■L
```

![你好-世界](https://github.com/pdfcpu/pdfcpu/assets/863369/40bff57a-067a-4f2a-af0f-14ee6358a1f1)

5\. `empty-opt.pdf` is a size-optimized version of `empty.pdf`, and it passes strict validation. But a panic happens when adding a keyword.

```
$ pdfcpu validate -m strict empty-opt.pdf
validating(mode=strict) empty-opt.pdf ...
validation ok
$ pdfcpu keywords add empty-opt.pdf hello
optimizing...
unexpected panic attack: runtime error: invalid memory address or nil pointer dereference
```

[testfiles.zip](https://github.com/user-attachments/files/16118254/testfiles.zip)

**Comment by hhrutter** [comment]
Thanks for reporting this!

**Comment by hhrutter** [comment]
This should be fixed with the latest commit!

**Comment by wdscxsj** [comment]
Thanks for your great work! But test 2 still fails; note the original "12" and "3" are repeated in the resulting PDF shown by Acrobat. Same for tests 3 and 4, where the Chinese text displays fine but also with the repetition.

**Comment by hhrutter** [comment]
Please try with the latest commit and report back!

**Comment by wdscxsj** [comment]
Hello, thanks for the update! I think it's mostly correct now. One failing case is that, if multiple CJK strings with spaces are added, the order of the keyword listing is wrong, as shown by pdfcpu and Acrobat as well:

```
$ pdfcpu keywords add empty-你好.pdf "世 界" "大 同"
$ pdfcpu keywords list empty-你好.pdf
optimizing...
大 同
你好
世 界
```

The expected keyword listing is:

```
你好
世 界
大 同
```

**Comment by hhrutter** [comment]
The order is irrelevant.

**Comment by wdscxsj** [comment]
> The order is irrelevant.
Thanks for the reply! I suppose it'll feel better if the result is deterministic. Anyway, this issue is nicely resolved.

**Comment by hhrutter** [comment]
Thanks for your detailed input.

Please consider becoming a [pdfcpu sponsor](https://github.com/sponsors/hhrutter) 💚
