### ISSUE TITLE
Duplicated stamps

### ISSUE THREAD

**Issue by nhannh23** [pdfcpu/pdfcpu#930]
Hi @hhrutter 

I have a PDF file from a specific PDF Writer. I'm facing an issue of duplicated stamps when calling stamp multiple times.

#### Steps to reproduce:
1. Firstly, I stamp a random string on page `4` of the document
   ```
   pdfcpu stamp add -p 4 -m text -- "WORLDDDDDDDDDDDDDDDD" "rot:0,offset:100 -800,pos:tl,fillcolor:#ff0000" duplicated-stamp.pdf 1.pdf
   ``` 
2. Then, call another stamp command on page `3` with the produced PDF file from the first step, `1.pdf`
   ```
   pdfcpu stamp add -p 3 -m text -- "Hiiiiiiiiiiii" "rot:0,offset:100 -800,pos:tl,fillcolor:#ff0000" 1.pdf 1_1.pdf
   ``` 
#### Result:
 I'm seeing the word `Hiiiiiiiiiiii` is somehow duplicated on the page 3, which is not expected.

I will send you the sample file via email after submitting this issue. Thank you so much for the great tool!

### Thank you for submitting a possible bug!

Please ensure the following:

* Your issue is based on the latest commit
v0.8.0
* State your OS and OS version
macOS Sonoma 14.5
* When reporting a problem with a specific PDF input file please avoid stating the organization responsible for the PDFWriter - just refer to the *PDFWriter*

**Comment by hhrutter** [comment]
This should be fixed with the latest commit.

**Comment by nhannh23** [comment]
Hi @hhrutter 
Thanks for your time and effort on fixing it. However, the bug seems still happen.
- I pull the repo on my local
- I go to the folder `/cmd/pdfcpu`
- I copy the `duplicated-stamp.pdf` file into the folder.
- I run two below commands
```bash
go run . stamp add -p 3 -m text -- "Hiiiiiiiiiiii" "rot:0,offset:100 -700,pos:tl,fillcolor:#ff0000" duplicated-stamp.pdf 1.pdf

go run . stamp add -p 4 -m text -- "WORLDDDDDDDDDDDDDDDD" "rot:0,offset:100 -700,pos:tl,fillcolor:#ff0000" 1.pdf 1_1.pdf
```
- The final resulted `1_1.pdf` file still has duplicated stamps

Could you please help to check again? 🙏

**Comment by hhrutter** [comment]
You need to get the latest commit: b9c28ae9fc7ba0dd66a0842f2b063ce9c6ed79eb

**Comment by nhannh23** [comment]
I'm pretty sure I'm at the head now 🤔 
<img width="658" alt="Screenshot 2024-08-22 at 15 52 00" src="https://github.com/user-attachments/assets/6aac3568-b344-461d-a11f-3f06734a3f39">

**Comment by hhrutter** [comment]
ok, I'll double check.

**Comment by hhrutter** [comment]
Works for me..

Did you run `go install` in `pdfcpu/cmd/pdfcpu`after pulling?

Then use the command to run the installed binary: `pdfcpu stamp add etc.`

**Comment by nhannh23** [comment]
@hhrutter 
It's still happening from my side 😿 
I already tried `go install` inside `pdfcpu/cmd/pdfcpu` after pulling. I captured an image what I have done. You can see the latest version of the library.
Did you try to stamp in two different pages? In my test, I tried with the 3rd and 4th pages.
![Uploading Screenshot 2024-08-26 at 08.56.08.png…]()

**Comment by hhrutter** [comment]
`conf.Optimize` needs to be true for your stamping operation.
You do that in your `config.yml`.
Also check that your config.yml is the latest (https://pdfcpu.io/getting_started/config_dir)

**Comment by nhannh23** [comment]
Saved my life 🙏  I didn't realize I was using the default config for the whole time. Thank you so much.

Btw, can you give me some advices when handling custom config file with user fonts installed?

**Comment by nhannh23** [comment]
Please ignore my last question. I resolved it myself, but writing the custom configuration into the default yml file in the default configuration dir. Then fonts will work normally.

Thank you so much for the continued support.
